### ISSUE TITLE
Deep sleep mode

### ISSUE THREAD

**Issue by jkockx** [lemmi25/ESP32WiFiAP#1]
Did you look for a way without having to turn in Deep Sleep Mode first?

**Comment by lemmi25** [comment]
Hi, 
I turn into deep sleep in order to save the variables of SSID and PSW. Otherwise they would get lost and I can not connect to the AP. Does this help? Why are you looking for another way?

**Comment by jkockx** [comment]
I was looking around for a way to do it without having to turn into deep sleep mode just to diminish the delay when people (likely to miss type few times their ssid and pwd) are using the program to connect the esp32 to their home network. If I have some time left and find a way to do so, I'll let you know.
